#!/usr/bin/env bash
# Fail when tracked prose describes a repository that no longer exists.
#
# WHY: engine-state drift recurred after every engine landing (stub claims
# outlived both engines, and planning paths outlived the planning tree they
# pointed at). The narrower krites-extraction grep in ci.yml catches one
# phrasing of one ruling; this script catches the class: a cited
# workspace source path that is gone, or stub-era wording that only a
# pre-engine tree could make true.
#
# Two checks over tracked `.md`, `.toml`, `.txt`, `.rs`, and `.yml` files:
#
# 1. Cited workspace paths exist. The check covers `.rs`, `.md`, and
#    `.toml` paths that start with `crates/<member>/` (for a crate in this
#    workspace), `src/`, or `tests/`. A bare `src/...` or `tests/...` path
#    must exist under at least one workspace crate. Paths under a
#    non-member `crates/<name>/`, and paths preceded by another path
#    segment (`krites/src/...`, `./src/...`), are other repositories' or
#    relative paths and are skipped; name the repository when citing one.
# 2. No stub-era engine-state wording: a stub tied to an engine name,
#    a stub source file, or the phrasing that described the engines as
#    pending. Generic uses of "stub" elsewhere are not flagged.
#
# CHANGELOG.md is generated by release-please from historical commit
# subjects and is excluded from both checks, as is this script. Requires
# GNU grep (`-P`, `-Z`); any grep error fails the script rather than
# passing it.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

self="scripts/docs-drift.sh"
failed=0

mapfile -t members < <(git ls-files 'crates/*/Cargo.toml' | cut -d/ -f2 | sort -u)

is_member() {
  local candidate="$1" member
  for member in "${members[@]}"; do
    [[ "$member" == "$candidate" ]] && return 0
  done
  return 1
}

cited_path_exists() {
  local path="$1" member
  case "$path" in
    crates/*)
      local crate="${path#crates/}"
      crate="${crate%%/*}"
      is_member "$crate" || return 0
      [[ -e "$path" ]]
      ;;
    *)
      for member in "${members[@]}"; do
        [[ -e "crates/$member/$path" ]] && return 0
      done
      return 1
      ;;
  esac
}

# INVARIANT: grep exits 0 on a match, 1 on none, and 2 on an error. Only 0
# and 1 are results; anything else aborts so a missing `-P` cannot read as
# a clean tree.
run_grep() {
  local status=0
  grep "$@" || status=$?
  if [[ "$status" -gt 1 ]]; then
    echo "docs-drift: grep failed with status ${status}" >&2
    exit "$status"
  fi
}

mapfile -t prose < <(git ls-files '*.md' '*.toml' '*.txt' '*.rs' '*.yml' \
  | grep -vxF -e CHANGELOG.md -e "$self")

# WHY: `-Z` separates each file name with a NUL byte so a name containing
# `:` still parses; command substitution drops NUL bytes, so the matches go
# through a temporary file instead of a variable.
citations="$(mktemp)"
trap 'rm -f "$citations"' EXIT
run_grep -HnoPZ '(?<![\w./-])(crates|src|tests)/[\w./-]+\.(rs|md|toml)' "${prose[@]}" >"$citations"
while IFS= read -r -d '' file && IFS=: read -r line path; do
  if ! cited_path_exists "$path"; then
    echo "::error file=${file},line=${line}::cites ${path}, which does not exist in this workspace"
    failed=1
  fi
done <"$citations"

engine='(hnsw|bm25|fts|vector index|full-text)'
stale="stub\\.rs|${engine}[^.;]{0,80}\\bstubs?\\b|\\bstubs?\\b[^.;]{0,80}${engine}|stubbed pending|#\\[ignore = \"phase 2|remains unavailable until|pending (its|a) fresh (graph )?implementation"
stale_hits="$(run_grep -HniE "$stale" "${prose[@]}")"
while IFS= read -r hit; do
  [[ -z "$hit" ]] && continue
  echo "::error::stub-era engine-state wording: ${hit}"
  failed=1
done <<<"$stale_hits"

if [[ "$failed" -ne 0 ]]; then
  echo "Docs describe a tree that no longer exists; update the prose to the shipped state." >&2
  exit 1
fi
echo "docs-drift: cited paths resolve and no stub-era wording remains"
