#!/usr/bin/env bash
# Fail when tracked prose describes a repository that no longer exists.
#
# WHY: engine-state drift recurred after every engine landing (stub claims
# outlived both engines, and planning paths outlived the planning tree they
# pointed at). The narrower krites-extraction grep in ci.yml catches one
# phrasing of one ruling; this script catches the class: a cited
# workspace source path that is gone, or stub-era wording that only a
# pre-engine tree could make true.
#
# Two checks, both over tracked files only (`git ls-files`):
#
# 1. Cited workspace paths exist. A `crates/<member>/...` citation must
#    exist when `<member>` is a crate in this workspace; a bare `src/...` or
#    `tests/...` citation must exist under at least one workspace crate.
#    Other repositories' paths must name their repository (for example
#    `krites/src/...` or `crates/basanos/...` qualified by "in
#    forkwright/kanon"); a path preceded by another path segment is not
#    treated as a workspace citation.
# 2. No stub-era engine-state wording. The phrases below were only true
#    before the HNSW and BM25 engines landed.
#
# CHANGELOG.md is generated by release-please from historical commit
# subjects and is excluded from both checks, as is this script.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

self="scripts/docs-drift.sh"
failed=0

mapfile -t members < <(git ls-files 'crates/*/Cargo.toml' | cut -d/ -f2 | sort -u)

is_member() {
  local candidate="$1" member
  for member in "${members[@]}"; do
    [[ "$member" == "$candidate" ]] && return 0
  done
  return 1
}

cited_path_exists() {
  local path="$1" member
  case "$path" in
    crates/*)
      local crate="${path#crates/}"
      crate="${crate%%/*}"
      is_member "$crate" || return 0
      [[ -e "$path" ]]
      ;;
    *)
      for member in "${members[@]}"; do
        [[ -e "crates/$member/$path" ]] && return 0
      done
      return 1
      ;;
  esac
}

mapfile -t prose < <(git ls-files '*.md' '*.toml' '*.txt' '*.rs' '*.yml' \
  | grep -vxF -e CHANGELOG.md -e "$self")

while IFS=: read -r file line path; do
  if ! cited_path_exists "$path"; then
    echo "::error file=${file},line=${line}::cites ${path}, which does not exist in this workspace"
    failed=1
  fi
done < <(grep -noP '(?<![\w./-])(crates|src|tests)/[\w./-]+\.(rs|md|toml)' "${prose[@]}" || true)

stale='stub\.rs|typed stubs?\b|phase 1 (typed )?stub|stubbed pending|#\[ignore = "phase 2|remains unavailable until|pending (its|a) fresh (graph )?implementation'
while IFS= read -r hit; do
  echo "::error::stub-era engine-state wording: ${hit}"
  failed=1
done < <(grep -niE "$stale" "${prose[@]}" || true)

if [[ "$failed" -ne 0 ]]; then
  echo "Docs describe a tree that no longer exists; update the prose to the shipped state." >&2
  exit 1
fi
echo "docs-drift: cited paths resolve and no stub-era wording remains"
